<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function findAllWithFilterAndOrderQuery(array $filters, array $order=null)
    {
        $q = $this->createQueryBuilder('g')
            ->select('g,r')
            ->leftJoin('g.roles', 'r')
            ;

        if (!empty($filters['name'])) {
            $name = '%'.$filters['name'].'%';
            $q->andWhere('(g.name LIKE :name)')
                ->setParameter('name', $name);
        }

        return $q->getQuery();
    }
}
