# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    email_from_no_reply: 'no_reply@zennovia.com'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Extension para cargar los macros sin necesidad de agregar el import en cada twig
    App\Twig\MacroAutoloadTwigExtension:
        public: false
        tags:
            - { name: twig.extension }

    ##### ---- CONSTRAINTS
    App\Validator\Constraints\ValidateDependentFieldsValidator:
        tags:
            - { name: validator.constraint_validator, alias: app_validate_dependent_fields }

    ##### ---- ZENNOVIA COMMON
    Knp\Component\Pager\Paginator:
        autowire: true

    App\Zennovia\Common\BaseFormHandler:
        abstract: true
        public: false

    App\Zennovia\Common\EntityManagerHelper:
        autowire: true
        arguments: ['@doctrine.orm.entity_manager']

    App\Zennovia\Common\BaseSendMailHandler:
        autowire: true

    App\Zennovia\Common\FindEntitiesHelper:
        autowire: true

    ##### ---- SERVICES
    App\Service\Registration:
        calls:
            - [setFrom, ['%email_from_no_reply%']]

    App\Service\RecoverPassword:
        calls:
            - [setFrom, ['%email_from_no_reply%']]

    App\Service\SwitchUserSubscriber:
        class: App\Service\SwitchUserSubscriber
        arguments: ["@security.token_storage"]
        tags:
          - { name: kernel.event_subscriber }
