<?php

// This file was generated by running "composer dump-env prod"

return array (
    'APP_ENV' => 'dev',
    'APP_SECRET' => 'a01bdb2503c86b1bb3bad2ff71c19de5',
    'LOCALE' => 'es',
    'APP_DEBUG' => 'false',
    'MAILER_DSN' => 'smtp://localhost',
    'DATABASE_URL' => 'mysql://root:KI16zusemu@66.97.44.182:3306/asistencias2024?serverVersion=mariadb-10.4.11',
);
