<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '$ecretf0rt3st',
  'APP_DEBUG' => 'true',
  'DATABASE_URL' => 'mysql://root:KI16zusemu@66.97.44.182/jessica',
  'MAILER_URL' => 'smtp://mail.dev.zennovia.com?username=dev@dev.zennovia.com&password=desarrollo&port=587',
  'MAILER_DEV_EMAIL' => 'desarrollo@zennovia.com',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '955426918e81a8342e77f34efd6c256f',
  'BASE_PATH' => '',
  'PUBLIC_PATH' => '/build',
  'LINK_API' => 'http://geoentregas.sprint.com/api/',
  'PUBLIC_BUILD' => 'public/build',
  'SECURE_SCHEME' => 'http',
);
